"""Generate Frida scripts for native export and address tracing."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def generate_frida_native_trace_script(
    *,
    symbols: str | list[str] | None = None,
    addresses: str | list[str] | None = None,
    output: str | Path,
    capture_returns: bool = False,
    native_wait_seconds: float = 0.0,
    native_arg_preview: bool = False,
) -> dict[str, Any]:
    """Generate a Frida script that traces native exports or runtime addresses."""
    targets = []
    for symbol in _split_optional_values(symbols):
        targets.append(_parse_native_symbol(symbol))
    for address in _split_optional_values(addresses):
        targets.append({"kind": "address", "label": address, "address": address})
    if not targets:
        raise RuntimeError("at least one native symbol or address is required")
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wait_seconds = max(0.0, float(native_wait_seconds or 0.0))
    out_path.write_text(
        _render_native_trace_js(
            targets,
            capture_returns=capture_returns,
            native_wait_seconds=wait_seconds,
            native_arg_preview=native_arg_preview,
        ),
        encoding="utf-8",
    )
    return {
        "ok": True,
        "output": str(out_path),
        "target_count": len(targets),
        "capture_returns": capture_returns,
        "native_wait_seconds": wait_seconds,
        "native_arg_preview": native_arg_preview,
        "targets": targets,
    }


def _split_symbols(symbols: str | list[str]) -> list[str]:
    if isinstance(symbols, list):
        return [str(symbol).strip() for symbol in symbols if str(symbol).strip()]
    return [symbol.strip() for symbol in str(symbols).split(",") if symbol.strip()]


def _split_optional_values(values: str | list[str] | None) -> list[str]:
    if values is None:
        return []
    return _split_symbols(values)


def _parse_native_symbol(symbol: str) -> dict[str, Any]:
    module = ""
    name = symbol
    for separator in ("!", ":"):
        if separator in symbol:
            module, name = symbol.split(separator, 1)
            break
    name = name.strip()
    if not name:
        raise RuntimeError(f"invalid native symbol: {symbol!r}")
    label = f"{module.strip()}!{name}" if module.strip() else name
    return {
        "kind": "symbol",
        "label": label,
        "module": module.strip(),
        "symbol": name,
        "symbol_candidates": _native_symbol_candidates(name),
    }


def _native_symbol_candidates(symbol: str) -> list[str]:
    values = [symbol]
    if symbol.startswith("_") and len(symbol) > 1:
        values.append(symbol[1:])
    elif symbol:
        values.append(f"_{symbol}")
    return values


def _render_native_trace_js(
    targets: list[dict[str, Any]],
    capture_returns: bool,
    native_wait_seconds: float = 0.0,
    native_arg_preview: bool = False,
) -> str:
    targets_json = json.dumps(targets, indent=2)
    capture = "true" if capture_returns else "false"
    preview = "true" if native_arg_preview else "false"
    wait_ms = int(max(0.0, native_wait_seconds) * 1000)
    return f"""// Generated by ghidra-re.
// Run with: frida -p <pid> -l <this-file> --runtime=v8

const targets = {targets_json};
const captureReturns = {capture};
const nativeWaitMs = {wait_ms};
const nativeArgPreview = {preview};
const nativeArgPreviewMaxStringBytes = 160;
let hitIndex = 0;
const installedTargets = {{}};

function ptrString(value) {{
  try {{
    return value ? value.toString() : null;
  }} catch (error) {{
    return null;
  }}
}}

function moduleForAddress(address) {{
  try {{
    const module = Process.findModuleByAddress(address);
    if (!module) return null;
    return {{ name: module.name, base: ptrString(module.base), path: module.path }};
  }} catch (error) {{
    return null;
  }}
}}

function memoryRangeForAddress(address) {{
  try {{
    const range = Process.findRangeByAddress(address);
    if (!range) return null;
    return {{
      base: ptrString(range.base),
      size: range.size,
      protection: range.protection
    }};
  }} catch (error) {{
    return null;
  }}
}}

function sanitizePreviewString(value) {{
  try {{
    if (value === null || value === undefined) return value;
    return String(value).replace(/[\\u0000-\\u001f\\u007f]/g, function(ch) {{
      if (ch === "\\n") return "\\\\n";
      if (ch === "\\r") return "\\\\r";
      if (ch === "\\t") return "\\\\t";
      return "\\\\x" + ch.charCodeAt(0).toString(16).padStart(2, "0");
    }});
  }} catch (error) {{
    return "";
  }}
}}

function printableStringPrefix(value) {{
  try {{
    if (value === null || value === undefined) return "";
    const text = String(value);
    let prefix = "";
    for (let i = 0; i < text.length; i++) {{
      const ch = text[i];
      const code = ch.charCodeAt(0);
      if (ch === "\\uFFFD" || ch === "\\0") break;
      if (code < 0x20 || code === 0x7f) break;
      prefix += ch;
    }}
    return prefix;
  }} catch (error) {{
    return "";
  }}
}}

function readUtf8Preview(address) {{
  if (address && address.readCString) {{
    return address.readCString(nativeArgPreviewMaxStringBytes);
  }}
  if (typeof Memory !== "undefined" && Memory.readCString) {{
    return Memory.readCString(address, nativeArgPreviewMaxStringBytes);
  }}
  if (address && address.readUtf8String) {{
    return address.readUtf8String();
  }}
  if (typeof Memory !== "undefined" && Memory.readUtf8String) {{
    return Memory.readUtf8String(address);
  }}
  throw new Error("no UTF-8 string reader available");
}}

function nativeArgPreviewForValue(value) {{
  const result = {{
    value: ptrString(value),
    kind: "unknown",
    readable: false
  }};
  let address = null;
  try {{
    address = ptr(value);
  }} catch (error) {{
    result.kind = "non_pointer";
    result.error = String(error);
    return result;
  }}
  if (!address || address.isNull()) {{
    result.kind = "null";
    return result;
  }}
  try {{
    if (address.compare(ptr("0x10000")) < 0) {{
      result.kind = "small_scalar_or_tagged_pointer";
      return result;
    }}
  }} catch (error) {{}}
  const module = moduleForAddress(address);
  if (module) {{
    result.module = module;
    result.kind = "code_or_module_pointer";
  }}
  const range = memoryRangeForAddress(address);
  if (!range) {{
    if (result.kind === "unknown") result.kind = "unmapped_pointer_or_scalar";
    return result;
  }}
  result.range = range;
  result.readable = String(range.protection || "").indexOf("r") !== -1;
  if (!result.readable) {{
    if (result.kind === "unknown") result.kind = "nonreadable_pointer";
    return result;
  }}
  try {{
    const text = readUtf8Preview(address);
    if (text !== null && text !== undefined) {{
      const prefix = printableStringPrefix(text);
      if (prefix.length >= 3) {{
        result.utf8_string = sanitizePreviewString(prefix);
        result.utf8_truncated_at_bytes = nativeArgPreviewMaxStringBytes;
        result.utf8_prefix_truncated = prefix.length < String(text).length;
        result.kind = "utf8_string";
      }} else {{
        result.string_preview_status = "not_printable";
        if (result.kind === "unknown") result.kind = "readable_pointer";
      }}
    }} else if (result.kind === "unknown") {{
      result.kind = "readable_pointer";
    }}
  }} catch (error) {{
    result.read_error = String(error);
    if (result.kind === "unknown") result.kind = "readable_pointer";
  }}
  return result;
}}

function nativeArgPreviews(args) {{
  const previews = {{}};
  if (!nativeArgPreview) return previews;
  for (let i = 0; i < 8; i++) {{
    previews["x" + i] = nativeArgPreviewForValue(args[i]);
  }}
  return previews;
}}

function findExport(target) {{
  const candidates = target.symbol_candidates || symbolCandidates(target.symbol);
  const moduleName = target.module || null;
  for (const symbol of candidates) {{
    if (moduleName) {{
      try {{
        const module = Process.getModuleByName(moduleName);
        if (module && module.findExportByName) {{
          const address = module.findExportByName(symbol);
          if (address) return address;
        }}
      }} catch (error) {{}}
    }}
    try {{
      if (Module.findExportByName) {{
        const address = Module.findExportByName(moduleName, symbol);
        if (address) return address;
      }}
    }} catch (error) {{}}
    try {{
      if (Module.getExportByName) {{
        return Module.getExportByName(moduleName, symbol);
      }}
    }} catch (error) {{}}
    try {{
      for (const module of Process.enumerateModules()) {{
        if (moduleName && module.name !== moduleName) continue;
        try {{
          if (module.findExportByName) {{
            const address = module.findExportByName(symbol);
            if (address) return address;
          }}
        }} catch (error) {{}}
      }}
    }} catch (error) {{}}
  }}
  return null;
}}

function symbolCandidates(symbol) {{
  const values = [];
  function add(value) {{
    if (value && values.indexOf(value) === -1) values.push(value);
  }}
  add(symbol);
  if (symbol && symbol[0] === "_") {{
    add(symbol.slice(1));
  }} else if (symbol) {{
    add("_" + symbol);
  }}
  return values;
}}

function resolveTarget(target) {{
  if (target.kind === "address") {{
    try {{
      return ptr(target.address);
    }} catch (error) {{
      console.log("GHIDRA_FRIDA_NATIVE_ERROR " + target.label + " " + error);
      return null;
    }}
  }}
  return findExport(target);
}}

function installTarget(target) {{
  if (installedTargets[target.label]) return true;
  const address = resolveTarget(target);
  if (!address || address.isNull()) {{
    return false;
  }}
  Interceptor.attach(address, {{
    onEnter(args) {{
      this.ghidraHit = {{
        schema: "ghidra-re.runtime-hit.v1",
        tool: "frida",
        event_type: "native-call",
        hit_index: hitIndex++,
        timestamp_ms: Date.now(),
        symbol: target.symbol || target.label,
        target: {{
          kind: target.kind,
          label: target.label,
          symbol: target.symbol || "",
          module: target.module || "",
          address: ptrString(address)
        }},
        process: {{
          pid: Process.id,
          arch: Process.arch,
          platform: Process.platform
        }},
        runtime: {{
          pc: ptrString(this.context.pc),
          return_address: ptrString(this.returnAddress),
          hooked_address: ptrString(address),
          module: moduleForAddress(address)
        }},
        pc: ptrString(this.context.pc),
        return_address: ptrString(this.returnAddress),
        args: {{}}
      }};
      for (let i = 0; i < 8; i++) {{
        this.ghidraHit.args["x" + i] = ptrString(args[i]);
      }}
      if (nativeArgPreview) {{
        this.ghidraHit.native_arg_preview_mode = "best_effort_registers";
        this.ghidraHit.native_arg_previews = nativeArgPreviews(args);
      }}
      console.log("GHIDRA_FRIDA_HIT " + JSON.stringify(this.ghidraHit));
    }},
    onLeave(retval) {{
      if (!captureReturns || !this.ghidraHit) return;
      const event = {{
        schema: "ghidra-re.runtime-hit.v1",
        tool: "frida",
        event_type: "native-return",
        hit_index: this.ghidraHit.hit_index,
        symbol: target.symbol || target.label,
        target: this.ghidraHit.target,
        process: {{
          pid: Process.id,
          arch: Process.arch,
          platform: Process.platform
        }},
        return_value: ptrString(retval)
      }};
      console.log("GHIDRA_FRIDA_RETURN " + JSON.stringify(event));
    }}
  }});
  installedTargets[target.label] = true;
  console.log("GHIDRA_FRIDA_NATIVE_INSTALLED " + target.label + " " + ptrString(address));
  return true;
}}

console.log("GHIDRA_FRIDA_ENV " + JSON.stringify({{
  pid: Process.id,
  arch: Process.arch,
  platform: Process.platform,
  objcAvailable: (typeof ObjC !== "undefined") && ObjC.available,
  moduleCount: Process.enumerateModules().length
}}));

function emitMissingTargets() {{
  for (const target of targets) {{
    if (!installedTargets[target.label]) {{
      console.log("GHIDRA_FRIDA_NATIVE_MISSING " + target.label);
    }}
  }}
}}

const pendingTargets = [];
for (const target of targets) {{
  if (!installTarget(target)) pendingTargets.push(target);
}}

if (pendingTargets.length > 0) {{
  if (nativeWaitMs <= 0) {{
    emitMissingTargets();
  }} else {{
    const deadline = Date.now() + nativeWaitMs;
    const timer = setInterval(function() {{
      let remaining = 0;
      for (const target of pendingTargets) {{
        if (!installTarget(target)) remaining += 1;
      }}
      if (remaining === 0 || Date.now() >= deadline) {{
        clearInterval(timer);
        emitMissingTargets();
      }}
    }}, 50);
  }}
}}
"""
